name: exposure
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - boost-cpp=1.74.0=hc6e9bd1_2
  - branca=0.4.2=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - cfitsio=3.470=hb418390_7
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=pyhd8ed1ab_0
  - cudatoolkit=10.1.243=h036e899_8
  - curl=7.76.1=h979ede3_1
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h9c3ff4c_0
  - fiona=1.8.19=py38hdb5a769_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - future=0.18.2=py38h578d9bd_3
  - gdal=3.2.2=py38h507a4fd_3
  - geopandas=0.8.1=py_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=hcf90da6_5
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - hdf4=4.2.13=h10796ff_1005
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - importlib-metadata=4.0.1=py38h578d9bd_0
  - ipykernel=5.5.4=py38hd0cf306_0
  - ipyleaflet=0.13.6=pyhd8ed1ab_1
  - ipython=7.23.1=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kealib=1.4.14=hcc255d8_2
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libcurl=7.76.1=hc4aaa36_1
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgdal=3.2.2=hbf32332_3
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.2=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1013
  - liblapack=3.9.0=8_mkl
  - libnetcdf=4.8.0=nompi_hfa85936_101
  - libnghttp2=1.43.0=h812cca2_0
  - libpng=1.6.37=h21135ba_2
  - libpq=13.2=hfd2b0eb_2
  - libprotobuf=3.15.8=h780b84a_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_3
  - libspatialite=5.0.1=h20cb978_4
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.2.0=hdc55705_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h72842e0_4
  - libzip=1.7.3=h4de3113_0
  - llvm-openmp=11.1.0=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=2.0.0=py38h497a2fe_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py38h497a2fe_1003
  - mkl=2020.4=h726a3e6_304
  - munch=2.5.0=py_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.3.0=pyha770c72_1
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py38h1abd341_0
  - pandoc=2.12=h7f98852_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.1.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.03.0=h93df280_0
  - poppler-data=0.4.10=0
  - postgresql=13.2=h6303168_2
  - proj=8.0.0=h277dcde_0
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.0.1=py38hdf83a33_1
  - pyrsistent=0.17.3=py38h497a2fe_2
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.8.0=cpu_py38hd248515_1
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.0.3=py38h2035c66_1
  - readline=8.1=h46c0cb4_0
  - rtree=0.9.7=py38h02d302b_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - shapely=1.7.1=py38h4fc1155_4
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.35.5=h74cdb3f_0
  - terminado=0.9.5=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - tiledb=2.2.9=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing_extensions=3.7.4.3=py_0
  - tzcode=2021a=h7f98852_1
  - tzdata=2021a=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.0=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - -r file:requirements.txt
